# -*- coding: utf-8 -*-
"""Copy of Third party NLP Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1btpRFWpTI_PnCB0EBMgvFnpaVIGU7gB6
"""

# AI Third Party Risk Management project questionnaire for IT 745
# Install SteramLit


import streamlit as st
import pandas as pd
import json
from datetime import datetime

# Risk Questionnaire Configuration
# with open("risk_questionnaire_config.json", "r") as config_file:
#     config = json.load(config_file)
questions = {
    "q1": {"text": "Does the vendor have a formal cybersecurity policy?", "weight": 10},
    "q2": {"text": "Is data encrypted in transit and at rest?", "weight": 10},
    "q3": {"text": "Does the vendor perform regular vulnerability assessments?", "weight": 10},
    "q4": {"text": "Is multi-factor authentication (MFA) implemented?", "weight": 8},
    "q5": {"text": "Does the vendor comply with relevant regulations (e.g., GDPR, HIPAA)?", "weight": 10},
    "q6": {"text": "Does the vendor store or process sensitive data?", "weight": 7},
    "q7": {"text": "Does the vendor subcontract any critical services?", "weight": 8},
    "q8": {"text": "Is the vendor’s incident response plan tested annually?", "weight": 10},
    "q9": {"text": "Has the vendor experienced any recent data breaches?", "weight": 12},
    "q10": {"text": "Does the vendor provide employee cybersecurity training?", "weight": 5}

}

# Scoring and Risk Classification
def calculate_risk_score(responses, criticality):
    total_weight = sum(q["weight"] for q in questions.values())
    weighted_score = 0

    for key, response in responses.items():
        weight = questions[key]["weight"]
        if response == "Yes":
            weighted_score += weight
        elif response == "Partial":
            weighted_score += weight * 0.5

    score = (weighted_score / total_weight) * 100

    # Adjust for vendor criticality
    if criticality == "High":
        score *= 0.9
    elif criticality == "Low":
        score *= 1.1

    return min(100, max(0, score))


def classify_risk(score):
    if score < 50:
        return "High Risk"
    elif score < 75:
        return "Medium Risk"
    else:
        return "Low Risk"

        # AI-Based Recommendation Generator
def generate_recommendations(responses, risk_class):
    recs = []

    if risk_class == "High Risk":
        recs.append("Implement an immediate review of vendor cybersecurity practices and request evidence of remediation.")
        recs.append("Conduct an on-site or virtual audit focusing on access controls, encryption, and incident response.")
        recs.append("Require the vendor to establish a Service Level Agreement (SLA) for security monitoring and breach notification.")
    elif risk_class == "Medium Risk":
        recs.append("Request updated compliance certifications (e.g., SOC 2, ISO 27001) and review security documentation annually.")
        recs.append("Encourage the vendor to enhance MFA coverage and improve incident response testing frequency.")
    else:
        recs.append("Continue ongoing monitoring through annual assessments and periodic vulnerability scans.")
        recs.append("Maintain open communication with the vendor’s security team to ensure continuous compliance.")

    # Add AI-style adaptive insights based on answers
    if responses.get("q9") == "Yes":
        recs.append("Vendor has experienced a data breach — ensure post-incident corrective actions and data protection measures are verified.")
    if responses.get("q7") == "Yes":
        recs.append("Vendor uses subcontractors — verify that downstream providers adhere to equivalent security controls.")
    if responses.get("q10") == "No":
        recs.append("Lack of employee training identified — recommend mandatory annual cybersecurity awareness training.")

    return recs

# Streamlit UI
# ==============================================
st.set_page_config(page_title="AI-Driven Third-Party Risk Assessment", layout="centered")

st.title("🧠 AI-Driven Third-Party Risk Assessment Dashboard")
st.write("Assess vendor cybersecurity readiness and receive AI-generated recommendations for improvement.")

# Vendor Information
st.header("Vendor Information")
vendor = st.text_input("Vendor Name", "SampleVendorCo")
industry = st.text_input("Vendor Industry", "Finance")
criticality = st.selectbox("Vendor Criticality", ["High", "Medium", "Low"])

# Questionnaire
st.header("Risk Assessment Questionnaire")
responses = {}
for key, q in questions.items():
    responses[key] = st.radio(q["text"], ["Yes", "No", "Partial"], horizontal=True)

# Run Assessment
if st.button("Run AI-Driven Assessment"):
    score = calculate_risk_score(responses, criticality)
    risk_class = classify_risk(score)
    recommendations = generate_recommendations(responses, risk_class)
    timestamp = datetime.utcnow().isoformat() + "Z"

    result = {
        "vendor": vendor,
        "industry": industry,
        "criticality": criticality,
        "risk_score": round(score, 1),
        "risk_classification": risk_class,
        "recommendations": recommendations,
        "responses": responses,
        "timestamp": timestamp
    }

    # Results Display
    st.subheader("Assessment Results")
    st.metric("Risk Score", f"{round(score, 1)} / 100")
    st.metric("Risk Classification", risk_class)
    st.progress(int(score))

    st.write("###  AI-Generated Recommendations")
    for r in recommendations:
        st.markdown(f"- {r}")

    # Downloads
    json_data = json.dumps(result, indent=4)
    st.download_button(
        label="Download JSON Report",
        data=json_data,
        file_name=f"AI_TPRM_Report_{vendor}.json",
        mime="application/json"
    )

    df = pd.DataFrame([{
        "vendor": vendor,
        "industry": industry,
        "criticality": criticality,
        "risk_score": round(score, 1),
        "risk_classification": risk_class,
        "timestamp": timestamp
    }])
    csv_data = df.to_csv(index=False)
    st.download_button(
        label="Download CSV Summary",
        data=csv_data,
        file_name=f"AI_TPRM_Report_{vendor}.csv",
        mime="text/csv"
    )

st.markdown("---")
st.caption("Developed as part of AI-Driven Cybersecurity Research on Third-Party Risk Management © 2025")



